### ISSUE TITLE
.so not generate for other architecture

### ISSUE THREAD

**Issue by mansiJspaceo** [ejoker88/FFmpeg-3.4-Android#4]
how to generate .so for x86, x86_64, v8a for all this three architecture.
for this i use ffmpeg4.2.2 & ndk version 17c 

how to generate for this.

**Comment by ejoker88** [comment]
Hello,
did you already watched my video on Youtube (https://youtu.be/2OGbamEjYhc)? I have explained there every step. In build_all.sh file, please remove lines for other architecture. In your case you need to remove below lines. After that just follow my Tutorial. If you still encounter issues let me know.

chmod +x build_armeabi.sh
./build_armeabi.sh

chmod +x build_armeabi-v7a.sh
./build_armeabi-v7a.sh

**Comment by mansiJspaceo** [comment]
Thank you...
